# ~/.config/starship.toml
# Don't print a new line at the start of the prompt
add_newline = false

# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order = [
    "username",
    "hostname",
    "directory",
    "aws",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "character"
]
scan_timeout = 50

[username]
show_always = true
disabled = false


[hostname]
ssh_only = false
prefix = ""
suffix = ""
trim_at = "."
disabled = true

[directory]
# truncation_length = 256
fish_style_pwd_dir_length = 256
# truncate_to_repo = true
use_logical_path = true
prefix = ""
disabled = false

[aws]
style = "yellow"
symbol = ""
displayed_items = "all"
disabled = true

	[aws.region_aliases]
	eu-north-1 = "arn"
	eu-west-1 = "dub"

[git_branch]
symbol = ""
# truncation_length = 6
# truncation_symbol = "…"
disabled = false

[git_commit]
commit_hash_length = 7
prefix = ""
suffix = "…"
disabled = false

[git_state]

[git_status]
style = "bold yellow"
prefix = ""
suffix = ""

[line_break]
disabled = true


# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "$"     # The "symbol" segment is being set to "➜"
style_success = "bold green"
style_failure = "bold red"
disabled = false

[cmd_duration]
min_time = 200000
prefix = "took "
